"""Type stubs for Infernux.components.ref_wrappers."""

from __future__ import annotations

from typing import Any, Optional


class GameObjectRef:
    """Null-safe wrapper around a scene GameObject.

    Stores the persistent ``id`` (uint64, written into the .scene file) and
    lazily resolves the live C++ object each time it is accessed.
    """

    def __init__(
        self, game_object: Any = ..., *, persistent_id: int = ...
    ) -> None: ...

    @property
    def persistent_id(self) -> int:
        """The persistent ID stored in the scene file."""
        ...

    def resolve(self) -> Any:
        """Return the live GameObject, or ``None`` if destroyed/missing."""
        ...

    def __copy__(self) -> GameObjectRef: ...
    def __deepcopy__(self, memo: Any) -> GameObjectRef: ...
    def __getattr__(self, name: str) -> Any: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def instantiate(self, *args: Any, **kwargs: Any) -> Any:
        """Clone this referenced GameObject in the current scene."""
        ...


# MaterialRef is defined in Infernux.core.asset_ref and re-exported here.
from Infernux.core.asset_ref import MaterialRef as MaterialRef


class PrefabRef:
    """Reference to a prefab asset stored on disk.

    Stores the asset GUID and file-path hint of a ``.prefab`` file.
    Use :meth:`instantiate` to create a new scene object from the prefab.
    """

    def __init__(self, guid: str = ..., path_hint: str = ...) -> None: ...

    @property
    def guid(self) -> str:
        """The asset GUID from the .meta file."""
        ...
    @property
    def path_hint(self) -> str:
        """File path hint for locating the prefab."""
        ...
    @property
    def persistent_id(self) -> int:
        """Always 0 — a prefab has no scene-persistent ID."""
        ...
    @property
    def name(self) -> str:
        """Human-readable display name derived from the file path."""
        ...

    def resolve(self) -> None:
        """A prefab is not a live scene object — always returns ``None``."""
        ...
    def instantiate(self, *args: Any, **kwargs: Any) -> Any:
        """Create a new GameObject from this prefab in the active scene."""
        ...

    def __bool__(self) -> bool: ...
    def __copy__(self) -> PrefabRef: ...
    def __deepcopy__(self, memo: Any) -> PrefabRef: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...


class ComponentRef:
    """Null-safe reference to a component on a specific GameObject.

    Stores the target GameObject's persistent ID and the component type
    name.  Lazily resolves the live component instance at access time.
    """

    def __init__(self, *, go_id: int = ..., component_type: str = ...) -> None: ...

    def resolve(self) -> Any:
        """Return the live component instance, or ``None`` if unavailable."""
        ...

    @property
    def go_id(self) -> int:
        """The persistent ID of the target GameObject."""
        ...
    @property
    def component_type(self) -> str:
        """The type name of the referenced component."""
        ...
    @property
    def display_name(self) -> str:
        """Human-readable label for Inspector display."""
        ...

    def _serialize(self) -> dict: ...
    @classmethod
    def _from_dict(cls, data: dict) -> ComponentRef: ...

    def __copy__(self) -> ComponentRef: ...
    def __deepcopy__(self, memo: Any) -> ComponentRef: ...
    def __getattr__(self, name: str) -> Any: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
