from __future__ import annotations

from typing import Dict, Optional, Set, Type


def invalidate_discovery_cache() -> None: ...
def discover_pipelines() -> Dict[str, type]: ...
def discover_passes() -> Dict[str, type]: ...
