"""ConsolePanel — editor debug log viewer."""

from __future__ import annotations

from typing import Optional

from Infernux.lib import InxGUIContext
from Infernux.engine.ui.editor_panel import EditorPanel


class ConsolePanel(EditorPanel):
    """Displays Debug.Log / Warning / Error messages with filtering."""

    WINDOW_TYPE_ID: str
    WINDOW_DISPLAY_NAME: str

    def __init__(self, title: str = "Console") -> None: ...

    def save_state(self) -> dict: ...
    def load_state(self, data: dict) -> None: ...

    def set_play_mode_manager(self, manager: object) -> None: ...
    def set_status_bar(self, status_bar: object) -> None: ...
    def select_latest_entry(self) -> None: ...
    def log(self, message: str, level: str = "info") -> None: ...
    def clear(self) -> None: ...
    def on_render_content(self, ctx: InxGUIContext) -> None: ...
