from __future__ import annotations

from typing import Any


def prepare_component_icon_pixels(tex_data: Any) -> tuple[list[int], int, int]: ...
def bump_component_structure_version() -> None: ...
def get_component_structure_version() -> int: ...
def bump_inspector_value_generation() -> int: ...
def get_inspector_value_generation() -> int: ...
def record_inspector_profile_timing(bucket: str, elapsed_ms: float) -> None: ...
def record_inspector_profile_count(bucket: str, amount: float = 1.0) -> None: ...
def consume_inspector_profile_metrics() -> dict[str, float]: ...
def ensure_material_file_path(material: Any) -> str: ...